### ISSUE TITLE
Plex service not installed

### ISSUE THREAD

**Issue by mclacore** [TechieGuy12/PlexServerAutoUpdater#16]
Tried running this on my Plex server, and says Plex service not installed, so I can't run it. Which Plex service am I missing? Plex is running, so I don't really understand.

**Comment by robross0606** [comment]
Agreed, I have the same problem.  Does the service actually need to be named "Plex"?  That's a fairly important detail that is glossed right over.

**Comment by robross0606** [comment]
I figured that out but it wasn't clear. Are you simply looking for a specific service name ("PlexService"). Because there are other ways to shim Plex into a service besides that one Git project. For example, NSSM.

**Comment by TechieGuy12** [comment]
Sorry about not being clear.  I linked to the Plex forums for the service instead of the actual GitHub repo in the readme file.

At this time I am only looking for PlexServer, as I initially developed this app to work with that service (which is the one I use on my Plex server). I could eventually look at incorporating other methods of create a Plex service, however, that would require the user specifying the service name, as I couldn't use the path of the service as NSSM would just point to nssm.exe instead of the Plex executable.

**Comment by robross0606** [comment]
Service names can be changed so as long as we know you're dependent on a service named "PlexService" your app could work with other methods like NSSM.

**Comment by YouveGotMeowxy** [comment]
Is there a specific reason that plex must be run as a service for this updater to work?

**Comment by TechieGuy12** [comment]
I originally developed this app tonuodate Plex when it is running as a service using [PMSService](https://github.com/cjmurph/PM's Service) as there wasn't an easy way of updating manually.

Are you looking to update Plex if it is running as a process?
