### ISSUE TITLE
AutoUpdate not longer seeing new versions to update to

### ISSUE THREAD

**Issue by Eds1989** [TechieGuy12/PlexServerAutoUpdater#24]
Not sure if Plex have changed anything their end, but Plex is telling me that version 1.15.0.659 is available for download, but the updater tells me I am current on version 1.14.1.5488

Is it just me? Does the tool need updating?

**Comment by TechieGuy12** [comment]
I'm not sure what the issue is at this time. I am seeing the same issue on my server. There is a discussion about it in the Plex forums, where many are also seeing the previous version using the Plex API link. I'm not sure if the API link has been updated to get the latest versions of Plex.
I will keep looking to see what I can find.

**Comment by TechieGuy12** [comment]
I found the issue.

The latest version https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/0.1.7.1, has the fix.

**Comment by Eds1989** [comment]
Brilliant thanks!
